name: arkod_wp_api
description: A server app using the shelf package and Docker.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.0-182.2.beta <3.0.0"

dependencies:
  arkod_wp_core: ^0.0.4+1
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0
  args: ^2.3.1
  shelf: ^1.3.1
  shelf_router: ^1.1.3
  postgres: ^2.4.3
  http: ^0.13.4
  shelf_static: ^1.1.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.2
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0
  shelf_router_generator: ^1.0.3
