name: arkod_wp_api
description: A server app using the shelf package and Docker.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.17.0-182.2.beta <3.0.0"

dependencies:
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  args: ^2.0.0
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  postgres: ^2.4.3
  http: ^0.13.4
  arkod_wp_core:
    path: ../arkod_wp_core

dev_dependencies:
  lints: ^1.0.0
  test: ^1.15.0
  build_runner: ^2.1.8
  freezed: ^1.1.1
  json_serializable: ^6.1.4
  shelf_router_generator: ^1.0.2
