global:
  sendAnonymousUsage: false

log:
  level: INFO

api:
  insecure: false
  dashboard: true

entrypoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: web_secure
          scheme: https
  web_secure:
    address: ":443"
  database:
    address: ":5432"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    network: arkod-wp-network
    exposedByDefault: false
  file:
    filename: /etc/traefik/ssl.yaml
    watch: true