-- engines table definition

CREATE TYPE engine_type AS ENUM ('portainer');

CREATE TABLE engines (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp DEFAULT now() NOT NULL,
  is_initialized boolean DEFAULT false NOT NULL,
  name varchar(128) NOT NULL,
  host varchar(256) NOT NULL,
  type engine_type DEFAULT 'portainer' NOT NULL,
  api_key varchar(128)
);

-- local engine creation

INSERT INTO engines (name, host) VALUES ('local', 'portainer.arkod-wp.localhost');

-- websites table definition

CREATE TABLE websites (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp DEFAULT now() NOT NULL,
  name varchar(128) UNIQUE NOT NULL,
  title varchar(128) NOT NULL,
  admin_username varchar(128) NOT NULL,
  admin_password varchar(128) NOT NULL,
  admin_email varchar(256) NOT NULL,
  posts_url_structure varchar(128) NOT NULL,
  db_root_password varchar(128) NOT NULL,
  db_user varchar(128) NOT NULL,
  db_password varchar(128) NOT NULL,
  db_tables_prefix varchar(128) NOT NULL
);

-- environments definition

CREATE TABLE environments (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp DEFAULT now() NOT NULL,
  website_id int8 REFERENCES websites(id) NOT NULL,
  engine_id int8 REFERENCES engines(id) NOT NULL,
  endpoint_id int8 NOT NULL,
  stack_id int8 NOT NULL,
  website_url varchar(256) NOT NULL
);
