name: Build Docker image and publish to Docker Hub

on:
  push:
    tags:
      - "*.*.*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: List current directory
        run: ls -l

      - name: Checkout API source code
        uses: actions/checkout@v3
        with:
          path: arkod_wp_api

      - name: List current directory
        run: ls -l

      - name: Checkout ARKOD WordPress core package source code
        uses: actions/checkout@v3
        with:
          repository: arkod-team/arkod_wp_core
          path: arkod_wp_core
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: List current directory
        run: ls -l

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./arkod_wp_api
          push: true
          tags: arkod/arkod-wp-api:latest
