name: Build Docker image and publish to Docker Hub

on:
  push:
    tags:
      - "*.*.*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Get the version to build and publish
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: arkod/arkod-wp-api:latest,arkod/arkod-wp-api:${{ steps.get_version.outputs.VERSION }}
